.PHONY: default

default:
	make selftest1
	make selftest2

selftest1: selftest1-source-files/*
	cat selftest1-source-files/* >selftest1

selftest2: selftest2-source-files/*
	cat selftest2-source-files/* >selftest2
