#include "app.h"

CFStringRef char_name[256] = {

	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),
	CFSTR("question"),

	CFSTR("space"),	// 32
	CFSTR("exclam"),
	CFSTR("quotedbl"),
	CFSTR("numbersign"),
	CFSTR("dollar"),
	CFSTR("percent"),
	CFSTR("ampersand"),
	CFSTR("quotesingle"),
	CFSTR("parenleft"),
	CFSTR("parenright"),
	CFSTR("asterisk"),
	CFSTR("plus"),
	CFSTR("comma"),
	CFSTR("hyphen"),
	CFSTR("period"),
	CFSTR("slash"),
	CFSTR("zero"),
	CFSTR("one"),
	CFSTR("two"),
	CFSTR("three"),
	CFSTR("four"),
	CFSTR("five"),
	CFSTR("six"),
	CFSTR("seven"),
	CFSTR("eight"),
	CFSTR("nine"),
	CFSTR("colon"),
	CFSTR("semicolon"),
	CFSTR("less"),
	CFSTR("equal"),
	CFSTR("greater"),
	CFSTR("question"),
	CFSTR("at"),
	CFSTR("A"),
	CFSTR("B"),
	CFSTR("C"),
	CFSTR("D"),
	CFSTR("E"),
	CFSTR("F"),
	CFSTR("G"),
	CFSTR("H"),
	CFSTR("I"),
	CFSTR("J"),
	CFSTR("K"),
	CFSTR("L"),
	CFSTR("M"),
	CFSTR("N"),
	CFSTR("O"),
	CFSTR("P"),
	CFSTR("Q"),
	CFSTR("R"),
	CFSTR("S"),
	CFSTR("T"),
	CFSTR("U"),
	CFSTR("V"),
	CFSTR("W"),
	CFSTR("X"),
	CFSTR("Y"),
	CFSTR("Z"),
	CFSTR("bracketleft"),
	CFSTR("backslash"),
	CFSTR("bracketright"),
	CFSTR("asciicircum"),
	CFSTR("underscore"),
	CFSTR("grave"),
	CFSTR("a"),
	CFSTR("b"),
	CFSTR("c"),
	CFSTR("d"),
	CFSTR("e"),
	CFSTR("f"),
	CFSTR("g"),
	CFSTR("h"),
	CFSTR("i"),
	CFSTR("j"),
	CFSTR("k"),
	CFSTR("l"),
	CFSTR("m"),
	CFSTR("n"),
	CFSTR("o"),
	CFSTR("p"),
	CFSTR("q"),
	CFSTR("r"),
	CFSTR("s"),
	CFSTR("t"),
	CFSTR("u"),
	CFSTR("v"),
	CFSTR("w"),
	CFSTR("x"),
	CFSTR("y"),
	CFSTR("z"),
	CFSTR("braceleft"),
	CFSTR("bar"),
	CFSTR("braceright"),
	CFSTR("asciitilde"),
	CFSTR("controlDEL"),

	CFSTR("Alpha"),	// 128
	CFSTR("Beta"),
	CFSTR("Gamma"),
	CFSTR("Delta"),
	CFSTR("Epsilon"),
	CFSTR("Zeta"),
	CFSTR("Eta"),
	CFSTR("Theta"),
	CFSTR("Iota"),
	CFSTR("Kappa"),
	CFSTR("Lambda"),
	CFSTR("Mu"),
	CFSTR("Nu"),
	CFSTR("Xi"),
	CFSTR("Omicron"),
	CFSTR("Pi"),
	CFSTR("Rho"),
	CFSTR("Sigma"),
	CFSTR("Tau"),
	CFSTR("Upsilon"),
	CFSTR("Phi"),
	CFSTR("Chi"),
	CFSTR("Psi"),
	CFSTR("Omega"),

	CFSTR("alpha"),	// 152
	CFSTR("beta"),
	CFSTR("gamma"),
	CFSTR("delta"),
	CFSTR("epsilon"),
	CFSTR("zeta"),
	CFSTR("eta"),
	CFSTR("theta"),
	CFSTR("iota"),
	CFSTR("kappa"),
	CFSTR("lambda"),
	CFSTR("mu"),
	CFSTR("nu"),
	CFSTR("xi"),
	CFSTR("omicron"),
	CFSTR("pi"),
	CFSTR("rho"),
	CFSTR("sigma"),
	CFSTR("tau"),
	CFSTR("upsilon"),
	CFSTR("phi"),
	CFSTR("chi"),
	CFSTR("psi"),
	CFSTR("omega"),

	CFSTR("hbar"),		// 176
	CFSTR("multiply"),	// 177
	CFSTR("partialdiff"),	// 178
	CFSTR("minus"),		// 179
	CFSTR("greaterequal"),	// 180
	CFSTR("lessequal"),	// 181
	CFSTR("question"),	// 182
	CFSTR("question"),	// 183

	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
	CFSTR("question"),CFSTR("question"),CFSTR("question"),CFSTR("question"),
};

CFStringRef
get_char_name(int c)
{
	return char_name[c & 0xff];
}
